const START_FETCHING_CATEGORIES = 'redux/categories/START_FETCHING_CATEGORIES'
const SUCCESS_FETCHING_CATEGORIES = 'redux/categories/SUCCESS_FETCHING_CATEGORIES'
const ERROR_FETCHING_CATEGORIES = 'redux/categories/ERROR_FETCHING_CATEGORIES'