export const START_FETCHING_ORGANIZERS =
  "redux/organizer/START_FETCHING_ORGANIZERS";
export const SUCCCESS_FETCHING_ORGANIZERS =
  "redux/organizer/SUCCCESS_FETCHING_ORGANIZERS";
export const ERROR_FETCHING_ORGANIZERS =
  "redux/organizer/ERROR_FETCHING_ORGANIZERS";
